Implement bubble sort
edemagbenyo/bubble-sort-ruby pull request #1
Opened 2019-10-23 15:44 UTC by edemagbenyo

Bubble sort implementation in ruby using:
while loop
times method 
block

2019-10-23 18:39 UTC, samgaco requested changes
Hi @edemagbenyo and @kilonzi :high_brightness: 

Everything looks perfect and love the readme file :100: Just one thing left to correct:

- [ ]  bubble_sort_by should raise an error if no block is given

Please work on that and submit back for another code review. Regards! :muscle: 

----------------------------
* ###### STATUS OF THE PROJECT: REQUESTED CHANGES :stop_sign:

2019-10-23 18:39 UTC, samgaco commented on index.rb
> +  k.times do |i|
- [ ] **bubble_sort_by** should raise an error if no block is given

2019-10-23 20:24 UTC, stratospherique requested changes
### Great work implementing the suggested changes :clap: . However the project didn't follow the GitFlow guidelines. check below :arrow_down: 

- Since you are going to use this repo later in the program, you are supposed to create an intermediary branch "development" to which you are supposed to merge(i.e not master branch).
- create a development branch, set target branch of this pull request to be `development`

### That's it :relaxed: When finished, submit another code review request :pray: 

**Ahmed Mahfoudh**

2019-10-24 02:04 UTC, maelfosso requested changes
Hello,

Thank you for the improvement. The **Git Flow** process is OK now.
Just one bug to fix. Even if it's correctly running, the `raise error` it's not at the good position. Read the comment below, please.

Kindly make the changes and submit a new code review request.
Thanks.

**Mael FOSSO**
[Github](https://github.com) | [Twitter](https://twitter.com) | [LinkedIn](https://www.linkedin.com/in/mael-elvis-fosso-650b6346/)

2019-10-24 02:04 UTC, maelfosso commented on index.rb
> +      raise 'No block given. Please supply a block.' unless block_given?
It's not the good place.
Putting it here mean that you're going to test it every times in the while loop.
Think about put it before the starting the while loop or after ```def bubble_sort_by(arr)``` ?

2019-10-24 02:04 UTC, maelfosso commented on index.rb
> +bubble_sort([9, 7, 6, 5, 4, 3, 2, 1])
Not needed

2019-10-24 06:28 UTC, maelfosso approved these changes
# You did it :+1: The project is APPROVED :clap: 

You can merge it.
Good luck with the next step

**Mael FOSSO**
[Github](https://github.com) | [Twitter](https://twitter.com) | [LinkedIn](https://www.linkedin.com/in/mael-elvis-fosso-650b6346/)

2019-10-24 06:36 UTC, merged